export * from './lamp';
export * from './shelf';
export * from './storageBox';
export * from './extinguisher';
export * from './bakeryStand';
export * from './door';
export * from './displayPanel';
export * from './suspendedLamps';
export * from './stairs';
